#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

jqcpp="$cmd_dir/jqcpp"

echo "Running jqcpp help"
$jqcpp --help || panic "hello program failed"

echo ""


echo "======================================================="
echo "For example, you can run jqcpp like this: "
echo "echo '{\"name\": \"John\", \"age\": 35}' | $jqcpp '.age + 5'"
echo '{"name": "John", "age": 35}' | $jqcpp '.age + 5'
